### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by MrAwesomeRocks** [AlemSnyder/Fun-Game#14]
- https://github.com/gabime/spdlog
- https://github.com/google/glog
- https://github.com/amrayn/easyloggingpp
- https://github.com/log4cplus/log4cplus
- https://github.com/emilk/loguru
- https://github.com/odygrd/quill
- Boost::Log

**Comment by AlemSnyder** [comment]
- [ ] add logger (quill)
- [ ] configure logger
- [ ] remove print statements, and replace with logs
