### ISSUE TITLE
Add a scripting language

### ISSUE THREAD

**Issue by egelja** [AlemSnyder/Fun-Game#17]
## [Python](https://docs.python.org/3/extending/embedding.html)
Pros:
- It's Python, easy
- Can be extending with C
- Great editor support

Cons:
- Kinda a pain to write C exts
- Tutorial is several years old
- Not that fast
- Multiple DLLs

## [Lua](https://lucasklassmann.com/blog/2019-02-02-how-to-embeddeding-lua-in-c/)
Pros:
- Easy to embed and extend with C
- Lots of [documentation](https://www.lua.org/pil/24.html) on the issue
- Has a JIT compiler
- Single DLL

Cons:
- It's Lua, a very bare-bones language
- Wierd design choices
- Decent editor support, not like python

## Scheme
Pros:
- Very simple language and small interpreter
- Can be extended
- Some implementations compile to native code

Cons:
- Can be extended probably only by writing the interpreter
- Syntax looks like a bowl of oatmeal with fingernail clippings
- Not great editor support

**Comment by AlemSnyder** [comment]
what are you going to do with a scripting language? (add this to the issue)
you should try to get some code samples running with each language. HelloWorld, count to 10,000, etc.

**Comment by AlemSnyder** [comment]
What do you think about [this](http://chaiscript.com/docs.html)?

It has cpp syntax, and is made to be integrated into cpp. It seems ChaiScript is 3-10 times slower than Lua. As long as its not being called every frame should be fine.

**Comment by egelja** [comment]
No I think chai script is stupid. It has cpp syntax, with references, and the point of that is to enable optimizations. But it’s slower than Lua. So what’s the point of writing and thinking about these semantics if you can just write Lua and not think about it?

Take a look here. The top three languages are C, Lua, and Terra (aka Lua with memory management). https://github.com/r-lyeh-archived/scriptorium

So just use Lua.

**Comment by AlemSnyder** [comment]
#53 Lua is added.
